-- Wilaya / commune structurées
-- User.wilaya et Order.wilaya stockent désormais le CODE de la wilaya ("16"),
-- indépendant de la langue d'affichage (FR / AR). Voir lib/algeria.

ALTER TABLE "User"  ADD COLUMN "commune" TEXT;
ALTER TABLE "Order" ADD COLUMN "wilaya"  TEXT;
ALTER TABLE "Order" ADD COLUMN "commune" TEXT;

-- Conversion des anciennes valeurs (nom de wilaya) en code.
-- Idempotent : les lignes déjà au format code ne correspondent à aucun nom.
UPDATE "User" AS u
SET "wilaya" = m.code
FROM (VALUES
  ('Adrar', '01'),
  ('Chlef', '02'),
  ('Laghouat', '03'),
  ('Oum El Bouaghi', '04'),
  ('Batna', '05'),
  ('Béjaïa', '06'),
  ('Biskra', '07'),
  ('Béchar', '08'),
  ('Blida', '09'),
  ('Bouira', '10'),
  ('Tamanrasset', '11'),
  ('Tébessa', '12'),
  ('Tlemcen', '13'),
  ('Tiaret', '14'),
  ('Tizi Ouzou', '15'),
  ('Alger', '16'),
  ('Djelfa', '17'),
  ('Jijel', '18'),
  ('Sétif', '19'),
  ('Saïda', '20'),
  ('Skikda', '21'),
  ('Sidi Bel Abbès', '22'),
  ('Annaba', '23'),
  ('Guelma', '24'),
  ('Constantine', '25'),
  ('Médéa', '26'),
  ('Mostaganem', '27'),
  ('M''Sila', '28'),
  ('Mascara', '29'),
  ('Ouargla', '30'),
  ('Oran', '31'),
  ('El Bayadh', '32'),
  ('Illizi', '33'),
  ('Bordj Bou Arréridj', '34'),
  ('Boumerdès', '35'),
  ('El Tarf', '36'),
  ('Tindouf', '37'),
  ('Tissemsilt', '38'),
  ('El Oued', '39'),
  ('Khenchela', '40'),
  ('Souk Ahras', '41'),
  ('Tipaza', '42'),
  ('Mila', '43'),
  ('Aïn Defla', '44'),
  ('Naâma', '45'),
  ('Aïn Témouchent', '46'),
  ('Ghardaïa', '47'),
  ('Relizane', '48'),
  ('Bordj Bou Arreridj', '34'),
  ('Timimoun', '49'),
  ('Bordj Badji Mokhtar', '50'),
  ('Ouled Djellal', '51'),
  ('Béni Abbès', '52'),
  ('In Salah', '53'),
  ('In Guezzam', '54'),
  ('Touggourt', '55'),
  ('Djanet', '56'),
  ('El M''Ghair', '57'),
  ('El Meniaa', '58'),
  ('Aflou', '59'),
  ('Barika', '60'),
  ('El Kantara', '61'),
  ('Bir El Ater', '62'),
  ('El Aricha', '63'),
  ('Ksar Chellala', '64'),
  ('Aïn Oussara', '65'),
  ('Messaad', '66'),
  ('Ksar El Boukhari', '67'),
  ('Bou Saâda', '68'),
  ('El Abiodh Sidi Cheikh', '69'),
  ('أدرار', '01'),
  ('الشلف', '02'),
  ('الأغواط', '03'),
  ('أم البواقي', '04'),
  ('باتنة', '05'),
  ('بجاية', '06'),
  ('بسكرة', '07'),
  ('بشار', '08'),
  ('البليدة', '09'),
  ('البويرة', '10'),
  ('تمنراست', '11'),
  ('تبسة', '12'),
  ('تلمسان', '13'),
  ('تيارت', '14'),
  ('تيزي وزو', '15'),
  ('الجزائر', '16'),
  ('الجلفة', '17'),
  ('جيجل', '18'),
  ('سطيف', '19'),
  ('سعيدة', '20'),
  ('سكيكدة', '21'),
  ('سيدي بلعباس', '22'),
  ('عنابة', '23'),
  ('قالمة', '24'),
  ('قسنطينة', '25'),
  ('المدية', '26'),
  ('مستغانم', '27'),
  ('المسيلة', '28'),
  ('معسكر', '29'),
  ('ورقلة', '30'),
  ('وهران', '31'),
  ('البيض', '32'),
  ('إليزي', '33'),
  ('برج بوعريريج', '34'),
  ('بومرداس', '35'),
  ('الطارف', '36'),
  ('تندوف', '37'),
  ('تيسمسيلت', '38'),
  ('الوادي', '39'),
  ('خنشلة', '40'),
  ('سوق أهراس', '41'),
  ('تيبازة', '42'),
  ('ميلة', '43'),
  ('عين الدفلى', '44'),
  ('النعامة', '45'),
  ('عين تموشنت', '46'),
  ('غرداية', '47'),
  ('غليزان', '48'),
  ('تيميمون', '49'),
  ('برج باجي مختار', '50'),
  ('أولاد جلال', '51'),
  ('بني عباس', '52'),
  ('عين صالح', '53'),
  ('عين قزام', '54'),
  ('تقرت', '55'),
  ('جانت', '56'),
  ('المغير', '57'),
  ('المنيعة', '58'),
  ('أفلو', '59'),
  ('بريكة', '60'),
  ('القنطرة', '61'),
  ('بئر العاتر', '62'),
  ('العريشة', '63'),
  ('قصر الشلالة', '64'),
  ('عين وسارة', '65'),
  ('مسعد', '66'),
  ('قصر البخاري', '67'),
  ('بوسعادة', '68'),
  ('الأبيض سيدي الشيخ', '69')
) AS m(nom, code)
WHERE u."wilaya" = m.nom;
